[package]
name = "libgvls"
version = "0.1.2"
edition = "2024"

[dependencies]
tokio = { version = "1.51.1", features = ["rt-multi-thread", "process", "net", "sync", "macros"] }
serde = { version = "1.0.228", features = ["derive"] }
rustls = "0.23.37"
tokio-rustls = "0.26.4"
rcgen = "0.14.7"
remoc = "0.18.3"
futures-util = "0.3.32"
rtnetlink = "0.21.0"
netlink-packet-route = "0.30.0"
